"""empty message

Revision ID: 372f9fa99298
Revises: b130c3f6951c
Create Date: 2021-01-26 01:05:17.377889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372f9fa99298'
down_revision = 'b130c3f6951c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
